apiVersion: batch/v1
kind: Job
metadata:
  name: run-{{WORSKPACE_ID}}-cpp
spec:
  template:
    spec:
      containers:
      - name: cpp-runner
        image: gcc:latest
        command: ["bash", "-c", "g++ /workspace/main.cpp -o /workspace/main && /workspace/main"]
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace-volume
        hostPath:
          path: /cache/{{WORKSPACE_ID}}
          type: Directory
