apiVersion: batch/v1
kind: Job
metadata:
  name: run-{{WORSKPACE_ID}}-nodejs
spec:
  template:
    spec:
      containers:
      - name: nodejs-runner
        image: node:lts
        command: ["bash", "-c", "cd /workspace && npm run start"]
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace-volume
        hostPath:
          path: /cache/{{WORKSPACE_ID}}
          type: Directory