apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-{{WORKSPACE_ID}}-react
spec:
  replicas: 1
  matchLabels:
    app: react-runner
    ws: {{WORKSPACE_ID}}
  template:
    metadata:
      labels:
        app: react-runner
        ws: {{WORKSPACE_ID}}
    spec:
      containers:
      - name: react-runner
        image: node:lts
        command: ["bash", "-lc", "cd /workspace && npm install && npm run dev -- --host 0.0.0.0"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
        - name: workspace
          hostPath:
            path: /cache/{{WORKSPACE_ID}}
            type: Directory
