apiVersion: batch/v1
kind: Job
metadata:
  name: run-{{WORSKPACE_ID}}-cpp
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: cpp-runner
        image: gcc:latest
        command: ["bash", "-lc", "g++ /workspace/main.cpp -o /workspace/main && /workspace/main"]
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      restartPolicy: Never
      volumes:
      - name: workspace-volume
        hostPath:
          path: /cache/{{WORKSPACE_ID}}
          type: Directory
