apiVersion: batch/v1
kind: Job
metadata:
  name: run-{{WORSKPACE_ID}}-golang
spec:
  template:
    spec:
      containers:
      - name: golang-runner
        image: golang:1.24
        command: ["bash", "-c", "cd /workspace && go run main.go"]
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace-volume
        hostPath:
          path: /cache/{{WORKSPACE_ID}}
          type: Directory