apiVersion: batch/v1
kind: Job
metadata:
  name: run-{{WORSKPACE_ID}}-nodejs
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: nodejs-runner
        image: node:lts
        command: ["bash", "-c", "cd /workspace && npm run start"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      restartPolicy: Never
      volumes:
      - name: workspace
        hostPath:
          path: /cache/{{WORKSPACE_ID}}
          type: Directory