apiVersion: v1
kind: ServiceAccount
metadata:
  name: ide-backend-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ide-backend-role
  namespace: cloud-ide
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ide-backend-rolebinding
  namespace: cloud-ide
subjects:
- kind: ServiceAccount
  name: ide-backend-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: ide-backend-role
  apiGroup: rbac.authorization.k8s.io
