name: Build and push language shell images

on:
  push:
    paths:
      - 'backend/images/**'
    worfkflow_dispatch:

  permissions:
    contents: read
    packages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: golang
          path: images/golang
          tag: shell-golang-{{ github.sha }}
        - name: cpp
          path: images/cpp
          tag: shell-cpp-{{ github.sha }}
        - name: python
          path: images/python
          tag: shell-python-{{ github.sha }}
        - name: nodejs
          path: images/nodejs
          tag: shell-nodejs-{{ github.sha }}
        - name: react
          path: images/react
          tag: shell-react-{{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU (multi-arch, optional)
        uses: docker/setup-qemu-action@v2
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.path }}
        file: ${{ matrix.path }}/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:{{ github.sha }}

    - name: Smoke test (quick)
      run: |
        docker run --rm ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }} sh -c "echo smoke; exit 0"