name: Build and push language shell images

on:
  push:
    paths:
      - 'backend/images/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: golang
            path: backend/images/golang
            image_name: shell-golang
          - name: cpp
            path: backend/images/cpp
            image_name: shell-cpp
          - name: python
            path: backend/images/python
            image_name: shell-python
          - name: nodejs
            path: backend/images/nodejs
            image_name: shell-nodejs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch, optional)
        uses: docker/setup-qemu-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }}

      - name: Smoke test (quick)
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }} sh -c "echo smoke; exit 0"
